# =============================================================================
# Hyprland
# =============================================================================

# Programs
$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun

# Autostart
exec-once = hyprpaper &
exec-once = swaync

# Environment
env = XCURSOR_THEME, Bibata-Modern-Classic
env = XCURSOR_SIZE, 22
env = HYPRCURSOR_THEME, Bibata-Modern-Classic
env = HYPRCURSOR_SIZE, 22
env = TERM,xterm-256color
env = COLORTERM,truecolor

# Configuration
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/binds.conf

# Machine-specific configuration
source = ~/.config/hypr/local.conf
