general {
    hide_cursor = true
    grace = 0
    fade_in = true
}

background {
    path = screenshot
    blur_size = 5
    blur_passes = 3
    brightness = 0.6
    contrast = 0.9
}

input-field {
    halign = center
    valign = center
    size = 380 42
    inner_color = rgba(1a1a1acc)
    outer_color = rgba(9a9a9aff)
    outline_thickness = 3
    font_color = rgba(eeeeeeff)
    dots_center = true
    fail_color = rgba(ff5555ff)
}
