background #121212
background_opacity 0.75
foreground #d0d0d0

color0 #1c1c1c
color7 #c0c0c0
color8 #808080
color15 #f5f5f5

allow_remote_control yes

paste_actions no-op

selection_foreground #d0d0d0
selection_background #3a3a3a

# Layout-independent Ctrl shortcuts for RU/US
map --allow-fallback=ascii ctrl+c send_key ctrl+c
map --allow-fallback=ascii ctrl+r send_key ctrl+r
map --allow-fallback=ascii ctrl+t send_key ctrl+t

# Useful for ble.sh/fzf multiline/navigation
map --allow-fallback=ascii ctrl+j send_key ctrl+j
map --allow-fallback=ascii ctrl+k send_key ctrl+k
